### ISSUE TITLE
[BUG] There is no way to exit video player

### ISSUE THREAD

**Issue by Avimitin** [reorx/minimal-bilibili#2]
There is no button to close the video player, and I've tried to clicking on the empty space at the edge of the video player, refreshing the browser, and waiting for the video to finish playing, and none of these methods have been able to close the video player. I can only close the page and reopen it to switch to a new video source.

**Comment by reorx** [comment]
The close button will show if you move the mouse to the top right of the
video frame.
[image: image.png]

It's indeed not very easy to find, I'll add the ability to close the video
when clicking on the empty space, making it more intuitive to operate.

Sincerely,
Xiao Meng
reorx.com

**Comment by Avimitin** [comment]
Thanks!
