### ISSUE TITLE
[Feature request] Firefox plugin

### ISSUE THREAD

**Issue by Avimitin** [reorx/minimal-bilibili#3]
It would be nice if you could upload this plugin to Firefox.

**Comment by reorx** [comment]
I'll try to make it tonight. Would be appreciated if you can write a blog post or channel message to introduce it.

**Comment by reorx** [comment]
The Addon has been released, from my development test the video playback seems to have some problems, please feedback for any issue you encountered 

https://addons.mozilla.org/addon/minimal-bilibili/
