### ISSUE TITLE
[Bug] unable to load any content

### ISSUE THREAD

**Issue by missuo** [reorx/minimal-bilibili#5]
<img width="1813" alt="Xnip2024-08-25_12-24-45" src="https://github.com/user-attachments/assets/79031504-ddc5-4087-968d-fb39519c66ce">

Version: `Chrome Web Store 1.5.0`

**Comment by reorx** [comment]
麻烦提供一下 console 的输出我看下

**Comment by missuo** [comment]
<img width="919" alt="image" src="https://github.com/user-attachments/assets/a1235393-9088-41ca-8b46-c171a19c3f32">

**Comment by reorx** [comment]
明白了，是屏蔽词功能造成的影响，没有设置屏蔽词把所有视频都屏蔽了 🤦

我去修复并发布一下，在此之前，临时的解决办法是随便设置一个屏蔽词：
![CleanShot 2024-08-26 at 10 54 20@2x](https://github.com/user-attachments/assets/e9eae9c1-8605-4141-a76b-313e6c7b9289)

**Comment by missuo** [comment]
好！

> 明白了，是屏蔽词功能造成的影响，没有设置屏蔽词把所有视频都屏蔽了 🤦
> 
> 我去修复并发布一下，在此之前，临时的解决办法是随便设置一个屏蔽词： ![CleanShot 2024-08-26 at 10 54 20@2x](https://private-user-images.githubusercontent.com/405972/361289120-e9eae9c1-8605-4141-a76b-313e6c7b9289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDExODEsIm5iZiI6MTcyNDY0MDg4MSwicGF0aCI6Ii80MDU5NzIvMzYxMjg5MTIwLWU5ZWFlOWMxLTg2MDUtNDE0MS1hNzZiLTMxM2U2YzdiOTI4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwMjU0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmQ4YWVjZTIxOWVhYzUyOWExMjQ5ZDg5ZGY5Nzg3YzEzNzU5MGVlNjAwYWJlNzdkZmJlYmQ3NjRiODU4NDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PUt_FFuNnwf44_a-epA5Qtxgk5Dsv3GXRpOJupJQZa0)

好

**Comment by missuo** [comment]
> 明白了，是屏蔽词功能造成的影响，没有设置屏蔽词把所有视频都屏蔽了 🤦
> 
> 我去修复并发布一下，在此之前，临时的解决办法是随便设置一个屏蔽词： ![CleanShot 2024-08-26 at 10 54 20@2x](https://private-user-images.githubusercontent.com/405972/361289120-e9eae9c1-8605-4141-a76b-313e6c7b9289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDExODEsIm5iZiI6MTcyNDY0MDg4MSwicGF0aCI6Ii80MDU5NzIvMzYxMjg5MTIwLWU5ZWFlOWMxLTg2MDUtNDE0MS1hNzZiLTMxM2U2YzdiOTI4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwMjU0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmQ4YWVjZTIxOWVhYzUyOWExMjQ5ZDg5ZGY5Nzg3YzEzNzU5MGVlNjAwYWJlNzdkZmJlYmQ3NjRiODU4NDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PUt_FFuNnwf44_a-epA5Qtxgk5Dsv3GXRpOJupJQZa0)

OK，确实可以了。

**Comment by reorx** [comment]
Version 1.5.1 has been published and is awaiting review.
